services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=public-company-sites'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cnr-anac'
    ports:
      - '5432'
