CREATE TABLE IF NOT EXISTS companies (
    id BIGSERIAL PRIMARY KEY,
    codice_ipa TEXT UNIQUE,
    denominazione_ente TEXT NOT NULL,
    codice_fiscale_ente TEXT,
    tipologia TEXT,
    codice_categoria TEXT,
    codice_natura TEXT,
    acronimo TEXT,
    sito_istituzionale TEXT,
    sorgente TEXT,
    data_cancellazione DATE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version INT DEFAULT 0);
